apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: us-east4-docker.pkg.dev/sleeper-446205/auth
        ports:
        - containerPort: 3001
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MONGODB_URI
          - name: JWT_EXPIRATION
            valueFrom:
              secretKeyRef:
                name: auth-expiration
                key: JWT_EXPIRATION
          - name: HTTP_PORT
            valueFrom:
              secretKeyRef:
                name: auth-http-port
                key: HTTP_PORT
          - name: TCP_PORT
            valueFrom:
              secretKeyRef:
                name: auth-tcp-port
                key: TCP_PORT