apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: us-east4-docker.pkg.dev/sleeper-446205/payments/production
        ports:
        - containerPort: 3003
        env:
          - name: NOTIFICATIONS_HOST
            valueFrom:
              secretKeyRef:
                name: notifications-host
                key: NOTIFICATIONS_HOST
          - name: NOTIFICATIONS_PORT
            valueFrom:
              secretKeyRef:
                name: notifications-port
                key: NOTIFICATIONS_PORT
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-key
                key: STRIPE_SECRET_KEY
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: payment-port
                key: PORT