apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: us-east4-docker.pkg.dev/sleeper-446205/payments/production
        ports:
        - containerPort: 3001
        env:
          - name: GOOGLE_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: google-client-id
                key: GOOGLE_OAUTH_CLIENT_ID
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google-client-secret
                key: GOOGLE_OAUTH_CLIENT_SECRET
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google-refresh-token
                key: GOOGLE_OAUTH_REFRESH_TOKEN
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: google-smtp-user
                key: SMTP_USER